#!/usr/bin/env python3
"""
CogNetAICL fine-tuning launcher.

Prepares the AICL corpus (generated by tools/corpus_generator.py) into the
two-file format the CogNet train_pipeline expects (wiki.train.raw +
wiki.valid.raw), then launches the standard training pipeline so the model
fine-tunes on AICL spec->code pairs instead of WikiText.

The corpus is split 90/10 into train/valid. The pipeline auto-caches the
tokenized IDs, so subsequent runs load instantly.

Usage:
    py train_aicl.py --corpus <path>/aicl_corpus.raw --steps 500 --ckpt_dir ckpt_aicl

    # if no --corpus given, generates a fresh corpus from the AICL compiler first
    py train_aicl.py --generate
"""

import argparse
import os
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
AICL_PYTHON = os.path.join(os.path.dirname(HERE), "ZCodeProject", ".aicl-ref", "python")


def ensure_corpus(corpus_path, force_regen=False):
    """Ensure the corpus exists; regenerate from the AICL compiler if missing."""
    if os.path.exists(corpus_path) and not force_regen:
        return corpus_path
    print(f"[train_aicl] generating corpus from AICL compiler...")
    gen = os.path.join(AICL_PYTHON, "tools", "corpus_generator.py")
    if not os.path.exists(gen):
        raise FileNotFoundError(
            f"corpus generator not found at {gen}. Run the AICL Phase D work first."
        )
    subprocess.run(
        [sys.executable, gen, "--out", corpus_path, "--targets", "python"],
        check=True, cwd=AICL_PYTHON,
    )
    return corpus_path


def prepare_wikitext_layout(corpus_path, data_dir, split=0.9):
    """Lay out the corpus as wiki.train.raw + wiki.valid.raw inside a fake
    wikitext-2-raw dir, so train_pipeline.load_data finds it naturally.

    Note: train_pipeline.py hardcodes data_dir as <script_dir>/data and only
    accepts --steps on its CLI. So we always write into that exact location
    regardless of the --data_dir flag, and invoke the pipeline with just
    --steps. Clear any cached .pt first so the new corpus tokenizes fresh.
    """
    with open(corpus_path, "r", encoding="utf-8") as f:
        text = f.read()
    cut = int(len(text) * split)
    # The pipeline looks for data/wikitext-2-raw/wiki.{train,valid}.raw
    pipeline_data = os.path.join(HERE, "data")
    wt_dir = os.path.join(pipeline_data, "wikitext-2-raw")
    os.makedirs(wt_dir, exist_ok=True)
    with open(os.path.join(wt_dir, "wiki.train.raw"), "w", encoding="utf-8") as f:
        f.write(text[:cut])
    with open(os.path.join(wt_dir, "wiki.valid.raw"), "w", encoding="utf-8") as f:
        f.write(text[cut:])
    # Clear tokenized cache so the new corpus is re-tokenized
    for cache in ("train_ids.pt", "valid_ids.pt"):
        c = os.path.join(HERE, "checkpoints", cache)
        if os.path.exists(c):
            os.remove(c)
    print(f"[train_aicl] corpus split: train={cut:,} chars, valid={len(text)-cut:,} chars")
    print(f"[train_aicl] wrote to {wt_dir}")
    return pipeline_data


def main():
    parser = argparse.ArgumentParser(description="Fine-tune CogNet on the AICL corpus.")
    parser.add_argument("--corpus", default=os.path.join(HERE, "aicl_corpus.raw"),
                        help="path to aicl_corpus.raw (regenerated if missing)")
    parser.add_argument("--generate", action="store_true",
                        help="force-regenerate the corpus before training")
    parser.add_argument("--data_dir", default=os.path.join(HERE, "data_aicl"))
    parser.add_argument("--ckpt_dir", default=os.path.join(HERE, "ckpt_aicl"))
    parser.add_argument("--steps", type=int, default=500)
    parser.add_argument("--seq_len", type=int, default=2048)
    parser.add_argument("--batch_size", type=int, default=4)
    # Pass through any extra args to train_pipeline (e.g. --lr, --no_cuda)
    args, passthrough = parser.parse_known_args()

    corpus = ensure_corpus(args.corpus, force_regen=args.generate)
    prepare_wikitext_layout(corpus, args.data_dir)

    # Launch the standard pipeline. train_pipeline.py only accepts --steps;
    # data_dir/ckpt_dir are hardcoded to <HERE>/data and <HERE>/checkpoints.
    cmd = [
        sys.executable, os.path.join(HERE, "train_pipeline.py"),
        "--steps", str(args.steps),
    ] + passthrough
    print("[train_aicl] launching:", " ".join(cmd))
    subprocess.run(cmd, check=True)


if __name__ == "__main__":
    main()
